server:
  port: 8089 #tomcat端口号
  servlet:
    context-path: /KAFKALOG #应用名，必须以/开头
###  kafka

## kafka
#spring.kafka.bootstrap-servers: 192.168.1.6:9092

spring.kafka.bootstrap-servers: 172.25.3.113:9097,172.25.3.114:9097,172.25.3.115:9097
spring.kafka.consumer.enable-auto-commit: false
spring.kafka.consumer.group-id: kafkaresultlog
spring.kafka.consumer.auto-offset-reset: latest
spring.kafka.consumer.max-poll-records: 100
spring.kafka.consumer.topic: cdr_viewLog



# 设置批量消费
spring.kafka.listener.type: batch
  # 批量消费每次最多消费多少条消息


spring:
  kafka:
    listener:
      concurrency=6:
  main:
    allow-bean-definition-overriding=true:










##---------------------自定义参数
##场景id
SceneId: Other
##物料ID
ItemSetId: 79

##行为上报地址
actionurl: http://172.25.3.107:30000/cess-data-13/data/api/data-access/13/117/items





